"""Pydantic schema for the final PRRecommendation produced by the synthesizer."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.analysis import Concern, PolicyViolation, SecurityFinding

_DISCLAIMER = (
    "This recommendation is generated by an automated analysis system. "
    "It is advisory only. The final approval decision always belongs to "
    "the human reviewer."
)


class Issue(BaseModel):
    """A single suggestion or improvement in the recommendation."""

    dimension: Literal["code", "security", "tests", "policy", "general"] = Field(
        description="Which analysis dimension surfaced this issue."
    )
    severity: Literal["critical", "high", "medium", "low", "info"] = Field(
        description="Severity level."
    )
    description: str = Field(description="Clear, actionable description of the issue.")
    file: str | None = Field(
        default=None, description="Affected file path, if applicable."
    )
    line_range: list[int] | None = Field(
        default=None, description="Affected line range [start, end], if applicable."
    )


class PRRecommendation(BaseModel):
    """Final structured recommendation report produced by PR Guardian.

    This is ADVISORY ONLY. The human reviewer makes the final decision.
    """

    recommendation: Literal[
        "Ready for Approval",
        "Needs Minor Changes",
        "Request Changes",
        "Manual Investigation Recommended",
    ] = Field(
        description=(
            "'Ready for Approval' = no blocking or significant issues found, PR looks good to merge; "
            "'Needs Minor Changes' = minor, non-blocking quality or style issues identified; "
            "'Request Changes' = critical security vulnerabilities, CI check failures, or blocking policy violations; "
            "'Manual Investigation Recommended' = low confidence due to truncated diffs, missing CI results, or system limitations."
        )
    )
    recommendation_reason: str = Field(
        description="A detailed explanation of why this specific recommendation was chosen."
    )
    confidence: Literal["high", "medium", "low"] = Field(
        description=(
            "Confidence in the recommendation based on available information. "
            "Low confidence may indicate a very large diff, missing CI results, "
            "or ambiguous context."
        )
    )
    summary: str = Field(
        description=(
            "3–5 sentence human-readable narrative synthesising all analysis "
            "dimensions into a coherent recommendation."
        )
    )
    security_findings: list[SecurityFinding] = Field(
        default_factory=list,
        description="All security findings (secrets, dangerous patterns, dependency issues, prompt injections).",
    )
    code_quality_findings: list[Concern] = Field(
        default_factory=list,
        description="Specific code quality issues (complexity, maintainability, duplication, naming).",
    )
    policy_findings: list[PolicyViolation] = Field(
        default_factory=list,
        description="All repository policy violations found.",
    )
    suggestions: list[Issue] = Field(
        default_factory=list,
        description="Non-blocking improvements worth considering but not required for approval.",
    )
    human_approval_required: bool = Field(
        default=True,
        description="Always True. Emphasizes that this automated report is advisory and requires human sign-off.",
    )
    disclaimer: str = Field(
        default=_DISCLAIMER,
        description="Standard advisory disclaimer — must always be included.",
    )
